<script src="<?=$subPath . '/assets/js/jquery-3.3.1.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/modernizr-3.6.0.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/plugins.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/bootstrap.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/magnific-popup.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/jquery-ui.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/wow.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/odometer.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/viewport.jquery.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/nice-select.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/owl.min.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/paroller.js'?>"></script>
    <script src="<?=$subPath . '/assets/js/main.js'?>"></script>